import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { Button, Stats } from "react-daisyui"
import { MainState } from "../components/mainState"
import { circuits } from "../helpers/circuits"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-5xl">Racer Day</h1>

        {circuits.map((circuit) => {
          return <MainState circuit={circuit}></MainState>
        })}
      </main>
    </div>
  )
}

export default Home
